apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: standard-application
version: 1.0.18
home: https://github.com/ManagedKube/helm-charts
icon: https://github.com/ManagedKube/helm-charts
maintainers:
  - name: Garland
    email: info@managedkube.com
